id: P007950
initial_creation_type: ocr
source_metadata:
  id: bdr:W23716
  title: མོ་དཔེ་སྣ་ཚོགས
  author: ''
  volumes:
    ab167b4552ef40e9a3acda637eb3e66a:
      image_group_id: I0882
      title: ''
      volume_number: 1
      total_pages: 280
ebook_metadata:
  title: མོ་དཔེ་སྣ་ཚོགས
  author: ''
  sku: P007950
  cover: cover.jpg
  layers:
  - pagination
