id: P007950
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:51:09.675980
source_metadata:
  id: bdr:W23716
  title: མོ་དཔེ་སྣ་ཚོགས
  author: ''
  volumes:
    ab167b4552ef40e9a3acda637eb3e66a:
      image_group_id: I0882
      title: ''
      volume_number: 1
      total_pages: 280
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
